services:

  # MTA server service running with postfix
  mta-server:
    build: ./mta-server
    container_name: mta_server
    environment:
      - MAIL_HOSTNAME=${MAIL_HOSTNAME}
    ports:
      - "25:25"    # SMTP
      - "587:587"  # SMTP Submission
      - "993:993"  # IMAP